### ISSUE TITLE
Does Not Work If Limit Set Via Custom Layout Update

### ISSUE THREAD

**Issue by sprankhub** [ProxiBlue/CatalogListFilters#3]
This does not work if you add the limit in the category edit page under `Custom Layout Update` as the used event `core_block_abstract_prepare_layout_before` is dispatched too early. Using the event `core_block_abstract_to_html_before` works, so you may want to switch to this event instead.

**Comment by ProxiBlue** [comment]
Well spotted. I will adjust as suggested.
